clq/clq/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path
urlpatterns = [
 
  path('admin/', admin.site.urls),
  path('', include('qindex.urls')),
      ]+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

clq/qindex/urls.py
from django.urls import include,path
from . import views

app_name = "qindex"

urlpatterns = [
     
     path('', views.home, name='home'),
     path('about', views.about, name='about'),
     path('bhome', views.bhome, name='bhome'),
     path('ehome', views.ehome, name='ehome'),
     path('qr', views.qr,name='qr'), 
     path('vspl/', views.vspl,name='vspl'),
     path('vbspl/', views.vbspl,name='vbspl'),
     path('bqr', views.bqr,name='bqr'), 
     path('tl', views.tl,name='tl'),
     path('btl', views.btl,name='btl'),
     path('tl1/', views.tl1,name='tl1'),
     path('tl2/', views.tl2,name='tl2'),
     path('tl3/', views.tl3,name='tl3'),
     path('tl4/', views.tl4,name='tl4'),
     path('tl5/', views.tl5,name='tl5'),
     path('tl6/', views.tl6,name='tl6'),
     path('tl7/', views.tl7,name='tl7'),
     path('btl1/', views.btl1,name='btl1'),
     path('btl2/', views.btl2,name='btl2'),
     path('btl3/', views.btl3,name='btl3'),
     path('contact/', views.contact,name='contact'),
     path('contact/contactsave', views.contactsave, name="contactsave"),
]

clq/qindex/models.py
from django.db import models
from django.db.models.fields import CharField,IntegerField,BooleanField
# Create your models here.


class topic(models.Model):
    t_id = models.CharField(max_length=500)
    tname=models.CharField(max_length=500)
    surano=models.IntegerField()
    suraname=models.CharField(max_length=100)
    verseno=models.IntegerField()
    verse=models.CharField(max_length=50000)

    def __str__(self) :
        return self.tname   
 
class btopic(models.Model):
    bt_id = models.CharField(max_length=500)
    btname=models.CharField(max_length=500)
    bsurano=models.IntegerField()
    bsuraname=models.CharField(max_length=100)
    bverseno=models.CharField(max_length=200)
    bverse=models.CharField(max_length=50000)

    def __str__(self) :
        return self.btname      

#=============================
class spl(models.Model):
    av=models.CharField(max_length=1000) #arabic verse
    eu=models.CharField(max_length=1000)#  pronunciation word by word
    v=models.CharField(max_length=50000) #English translation exact verse with surano and verse no
    q=models.CharField(max_length=50000) #question
    

    def __str__(self) :
        return self.v   
 
class bspl(models.Model):
    bav=models.CharField(max_length=10000) #arabic verse
    bu=models.CharField(max_length=10000)#  pronunciation word by word
    bv=models.CharField(max_length=50000) #bangla translation exact verse with surano and verse no
    bq=models.CharField(max_length=50000) #question and traditional translation
    

    def __str__(self) :
        return self.bv      
    
#===========================================       
class Contact(models.Model):
    name = models.CharField(max_length=50, null=True)
    email = models.EmailField(max_length=50, null=True)
    desc = models.TextField(max_length=5000, null=True)

    class Meta:
        verbose_name_plural = "Contacts"

clq/qindex/views.py
from django.shortcuts import render
from .models import  topic,Contact,btopic,spl,bspl

from django.shortcuts import render,redirect


from django.contrib import messages
from django.http import FileResponse
import io
from django.contrib.auth.models import User,auth
# Create your views here.
def home(request):
    return render(request,'home.html') 

def vspl(request):
     sp = spl.objects.all()
     context = { }
     return render(request,'spl.html',{'sp':sp}) 

def vbspl(request):
     bsp = bspl.objects.all()
     context = { }
     return render(request,'bspl.html',{'bsp':bsp}) 
    
def bhome(request):
    return render(request,'bhome.html') 

def ehome(request):
    return render(request,'ehome.html') 

def contact(request):
    return render(request,'contact.html') 
#========================================================= 
#@login_required(login_url="/login")
def contact(request):
    return render(request, "contact.html")
#========================================================= 

#@login_required(login_url="/login")
def contactsave(request):
    try:
        if request.method == "POST":
            name = request.POST["name"]
            email = request.POST["email"]
            desc = request.POST["desc"]
            values = Contact(name=name, email=email, desc=desc)
            values.save()
            messages.info(request, "Your message is saved and added to database. ")
            messages.info(request, "")
    except:
        pass
    return redirect("/contact")

#========================================================= 
def log(request):
    return render(request,'login.html')

def about(request):
    return render(request,'about.html')

def qr(request):
     tp = topic.objects.all().order_by('tname')
     context = { }
     return render(request,'quran.html',{'top':tp}) 

def bqr(request):
     btp = btopic.objects.all().order_by('btname')
     context = { }
     return render(request,'bquran.html',{'top':btp})       

def tl(request):
     tp = topic.objects.all()
     return render(request,'Topic_List.html',{'top':tp}) 
def btl(request):
     btp = btopic.objects.all()
     return render(request,'bTopic_List.html',{'top':btp}) 
 


def btl1(request):
     btp = btopic.objects.all().filter(btname='অশ্লীলকার্য')
     btname='অশ্লীলকার্য'
     return render(request,'btl1.html',{'top':btp, 'btname':btname})

def btl2(request):
     btp = btopic.objects.all().filter(btname='অসমান')
     btname='অসমান'
     return render(request,'btl1.html',{'top':btp, 'btname':btname})

def btl3(request):
     btp = btopic.objects.all().filter(btname='অলি-মুর্শিদ')
     btname='অলি-মুর্শিদ' 
     return render(request,'btl1.html',{'top':btp, 'btname':btname})


def tl1(request):
     tp = topic.objects.all().filter(tname='Abraham')
     tname='Abraham'
     return render(request,'tl1.html',{'top':tp,'tname':tname}) 

def tl2(request):
     tp = topic.objects.all().filter(tname='Lahab')
     tname='Lahab'
     return render(request,'tl1.html',{'top':tp,'tname':tname}) 

def tl3(request):
     tp = topic.objects.all().filter(tname='Ahad')
     tname='Ahad'
     return render(request,'tl1.html',{'top':tp,'tname':tname}) 

def tl4(request):
     tp = topic.objects.all().filter(tname='Indecencies')
     tname='Indecencies'
     return render(request,'tl1.html',{'top':tp,'tname':tname}) 

def tl5(request):
     tp = topic.objects.all().filter(tname='Do and don\'t')
     tname='Do and don\'t'
     return render(request,'tl1.html',{'top':tp,'tname':tname}) 

def tl6(request):
     tp = topic.objects.all().filter(tname='Notequal')
     tname = 'Not equal'
     return render(request,'tl1.html',{'top':tp, 'tname':tname}) 

def tl7(request):
     tp = topic.objects.all().filter(tname='Oli and Murshid')
     tname = 'Oli and Murshid'
     return render(request,'tl1.html',{'top':tp, 'tname':tname}) 




 

clq/qindex/templates/bTopic_List.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
 <!-- JavaScript Bundle with Popper -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>   
<style>
    table, th, td {
      border: 1px solid black;
    }
    table.center {
      margin-left: auto;
      margin-right: auto;
    }
    h1{
        text-align: center;
        color:blue;
                  }
    h2{
      text-align: center;
      color:red;
                }             
    h3{
      text-align: center;
      margin-left:0px;
      color:black;
                }
    a{
      text-align: center;
      color:red;
                }  
    x{
      margin-left: 20px;
      color:red;
                }                        
    </style>
    <title>Al Quran Topic List </title>
</head>
<body>
       <!--------------------Start navbar------------------------>
      
        <nav class="navbar sticky-top navbar-light-bg-light" style="background-color: #FFA07A;">
          <!--nav class="navbar navbar-expand-lg bg-dark">
          <nav class="navbar navbar-expand-lg" style="background-color: #FFA07A;"-->
        <!--nav class="navbar navbar-expand-lg bg-dark"-->
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'qindex:bhome' %}">Back</a>
           
            
        
            
       
          </div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="navbar-brand">
                  <a class="nav-link active" href=""></a>
                </li>
                
                <li class="navbar-brand">
                  <a class="nav-link active" href=" "></a>
                </li>
                <li class="navbar-brand">
                    <a class="nav-link active" href=""></a>
                  </li>
              </ul>
              </div>
          </div>
        </nav>
        <!--------------------End navbar------------------------>   
 
    {% block content %}
   
         {% endblock %}
            </div>
            
       
        </div>
        <form action="" method="">
            
            {% csrf_token %}
    <div class="container">
      <br><br>
        <h2 align="center">আল কোরআনঃ বিষয় ভিত্তিক আয়াত সূচি</h2><br> 
           
        <h1></h1>
             
          <div class="d-flex justify-content-center mt-3 login_container">
           <a  class="btn btn-primary w-25  btn" href="{% url 'qindex:btl1' %}">অশ্লীলকার্য</a>
         </div>
         <div class="d-flex justify-content-center mt-3 login_container">
          <a  class="btn btn-primary w-25  btn" href="{% url 'qindex:btl2' %}">সবাই সমান নয়</a> 
        </div>
        <div class="d-flex justify-content-center mt-3 login_container">
          <a  class="btn btn-primary w-25  btn" href="{% url 'qindex:btl3' %}">অলি ও মুর্শিদ</a> 
        </div>
        </div>
    </form>     
           
</body>
</html>

clq/qindex/templates/bhome.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
       
       <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>   
       <style>
           table, th, td {
             border: 1px solid black;
           }
           table.center {
             margin-left: auto;
             margin-right: auto;
           }
           h1{
               text-align: center;
               color:blue;
                         }
           h2{
             text-align: center;
             color:black;
                       }             
           h3{
             text-align: center;
             margin-left:0px;
             color:black;
                       }
           a{
             text-align: center;
             color:red;
                       }  
           x{
             margin-left: 20px;
             color:red;
                       }                        
           </style>
        <title>Bangla Home</title>   
    </head>
    <body>
      {% block content %}
       <!--------------------Start navbar------------------------>
       <nav class="navbar sticky-top navbar-light-bg-light" style="background-color: #FFA07A;">
        <!--nav class="navbar navbar-expand-lg" style="background-color: #FFA07A;">
         <nav class="navbar navbar-expand-lg bg-dark"-->
        
            <div class="container-fluid">
              <a class="navbar-brand"href="{% url 'qindex:home' %} ">Back</a>
                                             
                                
              
                      <a class="navbar-brand" href="{% url 'qindex:bqr' %}">Quran All</a>
             
                  
                
                      <a class="navbar-brand" href="{% url 'qindex:btl' %}">Topic List</a>
                   
                  
                      <a class="navbar-brand" href="{% url 'qindex:vbspl' %}">Request</a>
                    
              
                </div>
           
          </nav>
        <!--------------------End navbar------------------------>   

        <div id="name" style="word-spacing: 30px;">
            <h4></h4>
            <h4>  </h4>
            
           
        
        </div>  
        <section>
            <div>
                <img>
            </div>
            <div id="q"align="center">
                  <h6> তিনিই আপনার প্রতি কিতাব নাযিল করেছেন।<br><br>
                     তাতে কিছু আয়াত রয়েছে সুস্পষ্ট, <br><br>
                     সেগুলোই কিতাবের আসল অংশ। <br><br>
                     আর অন্যগুলো রূপক। <br><br>
                     সুতরাং যাদের অন্তরে কুটিলতা রয়েছে, তারা অনুসরণ করে ফিৎনা বিস্তার<br><br>
                      এবং অপব্যাখ্যার উদ্দেশে তন্মধ্যেকার রূপকগুলোর। <br><br>
                      আর সেগুলোর ব্যাখ্যা আল্লাহ ব্যতীত কেউ জানে না।<br><br>
                       আর যারা জ্ঞানে সুগভীর, তারা বলেনঃ আমরা এর প্রতি ঈমান এনেছি। <br><br>
                       এই সবই আমাদের পালনকর্তার পক্ষ থেকে অবতীর্ণ হয়েছে। <br><br>
                    আর বোধশক্তি সম্পন্নেরা ছাড়া অপর কেউ শিক্ষা গ্রহণ করে না। <br><br>[সুরা আলে ইমরান - ৩:৭] </h6>  
                  
            </div>
                      <h3> এই সবই আমাদের পালনকর্তার পক্ষ থেকে অবতীর্ণ হয়েছে।</h3> <br><br>
            <div id="q"align="center">
                   </div>
            <div id=""align="center">
                 
            </div>
                 <div id=""align="center">
                    <h1></h1>
                    <h1> </h1>
                 </div>
            
        </section>
        <br>
 <!--------------------Footer Start------------------------>

  <nav class="navbar navbar-expand-lg" style="background-color: #FFA07A;font-color: #fff;">
    <!--nav class="navbar navbar-expand-lg bg-dark"-->
  
  
      <div class="container-fluid">
  <h5 class="text-center"> Developed by Soft Ray.</h5>
</div>
<div class="container-fluid">
  <h5 class="text-center">  <a class="nav-link active" href="{% url 'qindex:about' %}">About</a></h5>
</div>
<div class="container-fluid">
  <h5 class="text-center"> <a class="nav-link active" href="{% url 'qindex:contact' %}">Contact Us</a></h5>
    </div>
</nav>
<!--------------------Footer End------------------------>      


     {% endblock %}
    </body>
</html>

clq/qindex/templates/bquran.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
   
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>   
   <style>
       table, th, td {
         border: 1px solid black;
       }
       table.center {
         margin-left: auto;
         margin-right: auto;
       }
       h1{
           text-align: center;
           color:blue;
                     }
       h2{
         text-align: center;
         color:red;
                   }             
       h3{
         text-align: center;
         margin-left:0px;
         color:black;
                   }
       a{
         text-align: center;
         color:red;
                   }  
       x{
         margin-left: 20px;
         color:red;
                   }                        
       </style>


    <title>Al Quran Topic Wise Data </title>
</head>
<body>
     <!--------------------Start navbar------------------------>
     <!--nav class="navbar navbar-expand-lg" style="background-color: #FFA07A;"-->
      <nav class="navbar sticky-top navbar-light-bg-light" style="background-color: #FFA07A;">
        <!--nav class="navbar navbar-expand-lg bg-dark"-->
          <div class="container-fluid">
           
            <a class="navbar-brand" href="{% url 'qindex:bhome' %}">Back</a>
          
            <a class="navbar-brand" href=" ">" সব টপিক একত্রে " </a>
         
          </div>
            
              </div>
          </div>
        </nav>
        <!--------------------End navbar------------------------>
    {% block content %}
    <div id="name" style="word-spacing: 30px;">
       
      
       </div>
    
    <form action="add" method=" GET"align="center">
            <div className="Report">
                {% csrf_token %}
                <h2> </h2><br>
                
                <table class="center" border="2" cellpadding="10">
                    <tr>
                        <td></td>
                        <td>বিষয়ের নাম</td>
                        
                        <td>সুরা নম্বর</td>
                        <td>সুরার নাম</td>
                        
                        <td>আয়াত </td> 
                        
                    </tr>
                {% for top in top %}
                    <tr>
                        <td></td>
                        <td>{{top.btname}}</td>
                        
                        <td>{{top.bsurano}}</td>
                        <td>{{top.bsuraname}}</td>
                       
                        <td>{{top.bverse}}</td>
                       
                    </tr>
    
                {% endfor %}
            </table>
            </form>
     
            </div>
            <br><br>
            <br><br>
   
                  <div>
                   
                  
                <a href="{% url 'qindex:home' %}">Home</a>
                          
                {% endblock %}
                  </div>
</body>
</html>

clq/qindex/templates/btl1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Al Quran Topic Wise Data </title>
    <style>
        table, th, td {
          border: 1px solid black;
        }
        table.center {
          margin-left: auto;
          margin-right: auto;
        }
        h1{
            text-align: center;
            color:blue;
                      }
        h2{
          text-align: center;
          color:red;
                    }             
        h3{
          text-align: center;
          margin-left:0px;
          color:black;
                    }
        a{
          text-align: center;
          color:red;
                    }  
        x{
          margin-left: 20px;
          color:red;
                    }                        
        </style>
</head>
<body>
    
  
      <h2><a href="{% url 'qindex:btl' %}">Back</a></h2><br>
      <h1>বিষয়ঃ {{ btname }}</h1>
        <form action="add" method=" GET"align="center">
            <div className="Report">
                {% csrf_token %}
                <h2> </h2><br>
                <table class="center" border="2" cellpadding="10">   
                <tr>
                      
                        <td>বিষয়ের নাম</td>
                       <td>সুরা নম্বর</td>
                        <td>সুরার নাম</td>
                        <td>আয়াত নং</td>
                        <td>আয়াত </td> 
                    </tr>
                {% for top in top %}
                    <tr>
                        <td>{{top.btname}}</td>
                        <td>{{top.bsurano}}</td>
                        <td>{{top.bsuraname}}</td>
                        <td>{{top.bverseno}}</td>
                        <td>{{top.bverse}}</td>
                      
                    </tr>
    
                {% endfor %}
            </table>
            </form>
                 </div>
              
                <br> <td></td>
                <td></td>   
                   
              </div><br><br>     
   
<!--------------------Footer Start------------------------>
<footer class="bg-success text-white position-relative">
	<p class="text-center">This part of this service provided by Soft Ray.</p>
  </footer>
  <!--------------------Footer End------------------------>
    <br>
 
    </body>
    </html>
                 
                        
                          
                           
                           
                                     
                           
                  
                        
                  
                  
                  
                  
                   
                  

clq/qindex/templates/ehome.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
       
       <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>   
       <style>
           table, th, td {
             border: 1px solid black;
           }
           table.center {
             margin-left: auto;
             margin-right: auto;
           }
           h1{
               text-align: center;
               color:blue;
                         }
           h2{
             text-align: center;
             color:black;
                       }             
           h3{
             text-align: center;
             margin-left:0px;
             color:black;
                       }
           a{
             text-align: center;
             color:red;
                       }  
           x{
             margin-left: 20px;
             color:red;
                       }                        
           </style>
        <title>English Home</title>   
    </head>
    <body>
      {% block content %}
       <!--------------------Start navbar------------------------>
    

        <nav class="navbar navbar-expand-lg" style="background-color: #FFA07A;font-color: #fff;">
          <!--nav class="navbar navbar-expand-lg bg-dark"-->
            <div class="container-fluid">
              <a class="navbar-brand"href="{% url 'qindex:home' %} ">Back</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
                      
              
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="navbar-brand">
                      <a class="navbar-brand" href="{% url 'qindex:qr' %}">Quran All</a>
                    </li>
                  
                    <li class="navbar-brand">
                      <a class="navbar-brand" href="{% url 'qindex:tl' %}">Topic List</a>
                    </li>
                    <li class="navbar-brand">
                      <a class="navbar-brand" href="{% url 'qindex:vspl' %}">Request</a>
                    </li>
                </ul>
                </div>
            </div>
          </nav>
        <!--------------------End navbar------------------------>   

        <div id="name" style="word-spacing: 30px;">
            <h4></h4>
            <h4>  </h4>
            
           
        
        </div>  
        <section>
            <div>
                <img>
            </div>
            <div id="q"align="center">
                  <h6>  It is He who revealed to you the Book.        </h6> 
                  <h6> Some of its verses are definitive; </h6> 
               <h6> they are the foundation of the Book,</h6> 
            <h6> and others are unspecific. </h6> 
            <h6>As for those in whose hearts is deviation, </h6> 
            <h6>they follow the unspecific part, seeking dissent,  </h6> 
            <h6>and seeking to derive an interpretation.</h6>
            <h6>But none knows its interpretation </h6>
            <h6>except God and those firmly rooted in knowledge say, </h6>
            <h6>“We believe in it; all is from our Lord.” </h6>
            <h6>But none recollects except those with understanding.</h6>
            </div>
           
            <div id=""align="center">
                 
            </div>
                 <div id=""align="center">
                    <h1>4:7</h1>
                    <h1> </h1>
                 </div>
            
        </section>
        {% endblock %}
        <br>  <br><br>  <br>
 <!--------------------Footer Start------------------------>
 {% block footer %}
<nav class="navbar navbar-expand-lg" style="background-color: #FFA07A;font-color: #fff;">
    <!--nav class="navbar navbar-expand-lg bg-dark"-->
  
  <div class="container-fluid">
    <h5 class="text-center"> Developed by Soft Ray.</h5>
  </div>
  <div class="container-fluid">
    <h5 class="text-center">  <a class="nav-link active" href="{% url 'qindex:about' %}">About</a></h5>
  </div>
  <div class="container-fluid">
    <h5 class="text-center"> <a class="nav-link active" href="{% url 'qindex:contact' %}">Contact Us</a></h5>
  </div>
  {% endblock %}
</nav>
<!--------------------Footer End------------------------>      

    </body>
</html>